### ISSUE TITLE
Some modules never start in production mode when startBlocks are different

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/substreams#152] opened 2023-01-20 21:15 UTC
Context:
When running a substreams with module A(store) and module B(mapper that depends on store A), requesting the outputModule to be "B":

Issue:
If module A and module B have different values for "Initial Block", the processing is broken in production-mode: no job for module "B" is ever scheduled, there are only lots of scheduled jobs for "A".

Workarounds:
* If we align those initial blocks, it fixes the issue and the processing works.
* If we run without production-mode, it also fixes the issue.

Somewhere around the scheduler or splitting into jobs, there must be a bug...

**Comment by sduchesneau** [comment] 2023-01-20 21:36
Issue was encountered with this:

* output_module: map_vault_asset_transfers
* on our public endpoint as well as our (internal unstable) endpoint

```
Package name: enzyme
Version: v0.1.0
Modules:
----
Name: map_vault_creations
Initial block: 11681281
Kind: map
Output Type: proto:enzyme.vaults.v1.Vaults
Hash: 09cb4894f6a467ce6810db708c34082b0c99d910

Name: map_vault_share_transfers
Initial block: 11681299
Kind: map
Output Type: proto:enzyme.vaults.v1.VaultShareTransfers
Hash: 11887fd2843408a1cbbd38385ec5a3ba85464d73

Name: map_vault_asset_transfers
Initial block: 11681299
Kind: map
Output Type: proto:enzyme.vaults.v1.VaultAssetTransfers
Hash: b67c69455e601910e96687f60453af0736a577d8

Name: store_vault_proxies
Initial block: 11681281
Kind: store
Value Type: string
Update Policy: UPDATE_POLICY_SET
Hash: 242fc4b2b5d4cf65b5d2cfd988b7ed2d2a2ff936
```

**Comment by fubhy** [comment] 2023-01-20 23:47
In production mode, I'm also seeing incorrectly formatted `typeUrls`:

```
ModuleOutput {
      name: 'map_vault_share_transfers',
      data: {
        case: 'mapOutput',
        value: Any {
          typeUrl: 'type.googleapis.com/proto:enzyme.vaults.v1.VaultShareTransfers',
          value: [Uint8Array]
        }
      }
	  ...
}
```

**Comment by fubhy** [comment] 2023-01-20 23:49
This issue is now also reproducible for me if all start blocks are actrually the same. So not sure if that's the cause actually.

**Comment by maoueh** [comment] 2023-04-03 15:29
The `proto` is fixed, what's the status for the rest of this issue?

**Comment by fubhy** [comment] 2023-04-03 15:36
The `proto` problem was indeed fixed by @jubeless. Thanks for that!

I can't reproduce the other issue anymore so that might've been fixed as a side effect of some other work.

**Comment by maoueh** [comment] 2023-04-03 16:08
Ok thanks, closing for now, re-open if needed.

**Closed by maoueh** 2023-04-03 16:08 UTC
Labels: bug
